from .ficha import Ficha
from .instructor import Instructor
from .aprendiz import Aprendiz
from .pregunta import Pregunta
from .evaluacion import Evaluacion
from .respuesta import Respuesta
from .ficha_instructor import FichaInstructor
from .aprendiz import Aprendiz
from .instructor import Instructor
from .pregunta import Pregunta
from .evaluacion import Evaluacion
from .ficha_instructor import FichaInstructor
from .respuesta import Respuesta
