from app.services.ficha_service import FichaService
from app.services.aprendiz_service import AprendizService
from app.services.instructor_service import InstructorService
from app.services.pregunta_service import PreguntaService
from app.services.evaluacion_service import EvaluacionService
from app.services.respuesta_service import RespuestaService
from app.services.ficha_instructor_service import FichaInstructorService